### PR TITLE
swupd-client: Disable recurring check-update

### PR DESCRIPTION
**Pull request by rojkov**
It's up to user to decide if `swupd check-update` needs to
run periodically. By default the periodic job should be disabled.

Signed-off-by: Dmitry Rozhkov dmitry.rozhkov@linux.intel.com

### CODE REVIEW

**Comment by pohly** [comment]
It is an Ostro decision to not enable that service, therefore the change should be in our meta-ostro .bbappend file. You can leave the FILES_${PN} unmodified, it's okay if that does not match anything.

Let me clarify why I prefer this: it is easy to disable the service, but re-enabling it is not if the base recipe already deletes the file from ${D}, therefore the default should be as in the upstream source.

**Comment by pohly** [comment]
Before you update the patch, pull meta-swupd3. I just made some changes to those .bbappends. Please also help review and check commit f577282, so far I have only done cursory checks myself.

**Comment by rojkov** [comment]
Thank you for explaining. I'm rebuilding on top of fresh meta-swupd3 to give it a new test run.

**Comment by rojkov** [comment]
Disabled `check-update.timer` in meta-ostro, not in meta-swupd.

**Comment by pohly** [comment]
Merged via cherry-picking.

**Pull request closed without merging**
