### PR TITLE
Stateless next: toybox fixes + SSL certs

### PR DESCRIPTION
**Pull request by pohly**

### CODE REVIEW

**Comment by pohly** [comment]
@juimonen please have a look.

**Comment by pohly** [comment]
Do not merge, I want to back-port the upstream Toybox fix and then drop the local workaround.

**Comment by pohly** [comment]
@juimonen: I tried the upstream Toybox fix and sed -e '$a\' still does not work. Reported upstream, patch updated with that tracking information.

This is now ready for merging. Please review and merge.

**Comment by juimonen** [comment]
looks good to me.

**Pull request merged**
