### PR TITLE
make connman to read main.conf from default dir

### PR DESCRIPTION
**Pull request by juimonen**
Give stateless default dir as sysconfdir to connman's
configure. So this change will discard any configuration
at the moment in /etc.

Signed-off-by: Jaska Uimonen jaska.uimonen@intel.com

### CODE REVIEW

**Comment by pohly** [comment]
This looks like the change that STATELESS_RELOCATE does automatically. Was there a reason for not using that?

**Comment by juimonen** [comment]
no reason, just me not seeing/remembering the whole relocate thing... I can do it with relocate

**Comment by pohly** [comment]
Please switch to STATELESS_RELOCATE.

**Comment by pohly** [comment]
And please rebase. This'll bring in a totally new "stateless" branch with toybox and swupd integrated. That's the base OS that we need to get working.

When building, you can use "bitbake ostro-image", but beware that it creates images named "ostro-image-noswupd" - see commit log.

**Pull request closed without merging**
